### ISSUE TITLE
where is your project's main java.

### ISSUE THREAD

**Issue by ghost** [zhangliangming/HappyPlayer-PC#1]
when I open the MainFrame.java.I can't  open the JFrame.  could you tell me how to open your main java.

**Comment by zhangliangming** [comment]
you can run  "com.happy.enterProgram.EnterProgram.java"  file to open  the jframe.

**Comment by ghost** [comment]
thanks ,I have found that and it run on my computer successful .good for you

**Comment by zhangliangming** [comment]
you are welcome
